<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\EFCoreControllers\**" />
    <Content Remove="Controllers\EFCoreControllers\**" />
    <EmbeddedResource Remove="Controllers\EFCoreControllers\**" />
    <None Remove="Controllers\EFCoreControllers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyGuitarShop.Common\MyGuitarShop.Common.csproj" />
    <ProjectReference Include="..\MyGuitarShop.Data.MongoDb\MyGuitarShop.Data.MongoDb.csproj" />
  </ItemGroup>

</Project>
